### ISSUE TITLE
Find DGGS cells for input geojson

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/AusPIX_DGGS_API#11]
Carried over from #5 and #4

Implement a flask endpoint in https://github.com/CSIRO-enviro-informatics/AusPIX_DGGS_API to evaluate a list of DGGS cell IDs from geojson input.

Endpoint: /search/find_dggs_cells_by_geojson

Input:
* geojson (string)
* dggs level resolution (int, e.g. 1-14)

Output:
* List of DGGS Cell IDs

**Comment by jyucsiro** [comment]
Propose using the python `geojson` library https://github.com/jazzband/geojson

**Comment by bellie888** [comment]
We discussed which format to use and geojson was selected.
I think that works out good because it easily opens in QGIS for spatial work, and has the ability to add an attribute easily.

I'm hoping the AusPIX DGGS reference can be added to a new "column" in the geojson output.
This way the source attribute is maintained through the whole process, with AusPIX Cell references, added on.

Note: a polygon may have a 100 cells, so the attributes of that one polygon will be repeated once for each DGGS cell. This seems a bit verbose, but this the power of integrating data using AusPIX. Because as datasets are added and integrated, various combinations divide the polygon up in different ways - all of which can be used for statistics and apportionment etc.

**Comment by bellie888** [comment]
Note: it is important to bring the point/line/polygon attributes along through the DGGS enablement process because this is the data we want to integrate. We need things like polygon name, polygon ID, area, population, etc.
We can then integrate this data with other AusPIX enabled data, based in the DGGS location at the resolution we desire.
Looking into geojson, it can do this much more cleanly than pyshp (shapefile) can. :)
If someone has 'sensitive' data then they can just provide an ID in their dataset attributes, and rejoin it later. But most users would want to automate the process as much as possible.

**Comment by jyucsiro** [comment]
Attributes are now carried over.
