### ISSUE TITLE
Determine user input constraints for finding DGGS cells

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/AusPIX_DGGS_API#12]
Figure out what resolution and extent allowed

**Comment by jyucsiro** [comment]
Web API should return by 10 seconds

**Comment by bellie888** [comment]
I have been thinking about this a bit.
There are at least 2 scenarios of use:

1.  A user comes to the API via web page, and uploads a file they want to be AusPIX DGGS enabled. An estimate of the time it will take can be given. If the file is too big the API can refuse it. They can wait for an email to say their job is finished and here is the download link . . .  The email address will help us identify our users and enable us to meet their needs.

2. A machine to machine query. Cannot wait, if it is too big - receive an error message back "too big".

Comments?
Cheers
Joe
PS this is off topic but geojson could keep all the attributes of the source file and add the DGGS cell reference as another attribute. However there will be many cell per polygon so there will be many more rows in the output, so that would need to be considered.

**Comment by benjaminleighton** [comment]
There probably does need to be an upper limit of extent and resolution. WPS (web processing services) provides a model for long running asynchronous jobs and there are probably other possible models. Whether machine to machine queries can wait depends on the requirements and implementation of the client end machine. @bellie888 I think you and I discussed performance AusPIX_DGGS improvements some time ago and, if i recall correctly, there is room for some significant gains. 

From my notes
> Perhaps of interest, in `dggs_in_poly.py` the final “cell centroid” in polygon test consumed very little time, iirc a couple of percent of total runtime, most time was spent in figuring which cells initial grid points fell into and then in calculating grid centroids. 

and

> Looking at the algorithm for filling a polygon with DGGS cells I’m wondering if the algorithm could be sped up as follows: 
>1.	Get bounding box of polygon of interest (same as now)
>2.	For the 4 points defining the bbox get the corresponding DGGS cells at the resolution of interest
>3.	For each of the DGGS cells defining the corners of the bounding boxes iterate across adjacent cells in east west or north south directions until cells meet. This would form a bounding box made of DGGS cells
>4.	From this then fill the bounding box using a similar walk across adjacent cells

**Comment by jyucsiro** [comment]
Extent and resolution would be enough to get an estimate of time. That might be simple enough to get started with. 

The API instances could be configured/tuned with some config file that specifies this so that each deployment could be customised depending on the machine spec. i.e. larger extent/resolution allowed on a bigger machine, vs something on a smaller machine.

**Comment by bellie888** [comment]
@benjaminleighton 
Hi Ben,

----------------------------------------------
Looking at the algorithm for filling a polygon with DGGS cells I’m wondering if the algorithm could be sped up as follows:

Get bounding box of polygon of interest (same as now)
For the 4 points defining the bbox get the corresponding DGGS cells at the resolution of interest
For each of the DGGS cells defining the corners of the bounding boxes iterate across adjacent cells in east west or north south directions until cells meet. This would form a bounding box made of DGGS cells
From this then fill the bounding box using a similar walk across adjacent cells
------------------------

Yes the DGGS engine does this in a function called something like cells-from-region. Give it the upper left and lower right in lat long WGS84 and it returns all the cells inside.

However this doesn't work in the southcap region "S" (the region from the middle of Tasmania southwards) There is a bug in the engine, so I use a workaround of making a grid of points in that area over the poly, and asking the engine for the DGGS cell for each point - filtering out duplicates (filtering is slow, needs to be a dictionary instead of a list)

**Comment by bellie888** [comment]
sorry I didn't mean to have big bold letters :)

**Comment by benjaminleighton** [comment]
No worries. I always mess up the formatting too! I've recently discovered there is a Preview tab to the right of the Write tab that is handy. I think you did mention the bug previously actually I just forgot or misinterpreted that. Yes @jyucsiro just an estimate would be good. Presumably we are seeing performance good enough for reasonable size features?

**Comment by dr-shorthair** [comment]
@bellie888 you can go back and fix it: 
![image](https://user-images.githubusercontent.com/608303/82975041-bd15b180-a01e-11ea-94a1-50b50f73683a.png)

**Comment by jyucsiro** [comment]
Add a line of documentation text to warn users that if the area is large and/or resolution too high then it may be delayed - add this to the Web API OpenAPI documentation, and the testmap HTML.

**Comment by jyucsiro** [comment]
Agreed to resolve this using a warning text to alert the user of delay. See https://github.com/CSIRO-enviro-informatics/AusPIX_DGGS_API/issues/42
